name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install
      - uses: sibiraj-s/action-eslint@v3
        with:
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'ts,tsx'
          annotations: true
